In [1]:
import numpy as np
import pandas as pd

1.- Cread un array de dos dimensiones de 5 filas y 3 columnas.
Sobre el array creado anteriormente, extraed:

In [2]:
bidimensional = np.random.rand(5, 3)
bidimensional

array([[0.5148818 , 0.50311072, 0.02821856],
       [0.53492658, 0.49414925, 0.58138712],
       [0.11596723, 0.4304443 , 0.99590271],
       [0.66703851, 0.9161969 , 0.2377953 ],
       [0.55033879, 0.51404069, 0.50744429]])

- El valor de la primera fila y la segunda columna.

In [3]:
bidimensional[0,1]

0.503110724035691

- Los valores de la segunda fila y las dos primeras columnas.

In [4]:
bidimensional[1,0:2]

array([0.53492658, 0.49414925])

- Extraed las filas pares (incluyendo la 0) y todas las columnas.

In [5]:
bidimensional[0::2,:]

array([[0.5148818 , 0.50311072, 0.02821856],
       [0.11596723, 0.4304443 , 0.99590271],
       [0.55033879, 0.51404069, 0.50744429]])

- Extraed los valores que sean mayores que 0.5.

In [6]:
bidimensional[bidimensional > 0.5]

array([0.5148818 , 0.50311072, 0.53492658, 0.58138712, 0.99590271,
       0.66703851, 0.9161969 , 0.55033879, 0.51404069, 0.50744429])

- Extraed los valores menores que 0.2 o mayores que 0.5

In [9]:
bidimensional[(bidimensional < 0.2) | (bidimensional > 0.5)]

array([0.5148818 , 0.50311072, 0.02821856, 0.53492658, 0.58138712,
       0.11596723, 0.99590271, 0.66703851, 0.9161969 , 0.55033879,
       0.51404069, 0.50744429])

2.- Cread dos array de tres dimensiones:
El primero de 2 matrices, 5 filas y 3 columnas.
El segundo de 3 matrices, 2 filas y 5 columnas.

In [15]:
primer_array = np.random.randint(20,40,(2,5,3))
primer_array

array([[[34, 23, 25],
        [24, 39, 36],
        [28, 38, 38],
        [31, 32, 29],
        [32, 20, 29]],

       [[32, 31, 23],
        [20, 27, 30],
        [37, 24, 23],
        [38, 29, 25],
        [38, 26, 33]]])

In [17]:
segundo_array = np.random.randint(20,40,(3,2,5))
segundo_array

array([[[29, 20, 26, 39, 33],
        [30, 35, 34, 28, 32]],

       [[24, 22, 34, 33, 32],
        [28, 26, 36, 28, 26]],

       [[36, 27, 32, 24, 25],
        [23, 34, 29, 31, 24]]])

Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [49]:
def propiedades_array(array):
    tipo=f"Los elementos son de tipo {array.dtype}"
    tamaño=f"Tiene {array.size} elementos"
    forma=f"Su forma es: {array.shape}"
    dimension=f"Es de {array.ndim} dimensiones"
    return tipo,tamaño,forma,dimension

In [50]:
propiedades_array (primer_array)

('Los elementos son de tipo int64',
 'Tiene 30 elementos',
 'Su forma es: (2, 5, 3)',
 'Es de 3 dimensiones')

In [51]:
propiedades_array (segundo_array)

('Los elementos son de tipo int64',
 'Tiene 30 elementos',
 'Su forma es: (3, 2, 5)',
 'Es de 3 dimensiones')

Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [ ]:
No se puede por que no tienen la misma forma.

Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas
formas hemos aprendido dos métodos:
- .reshape()
- .transpose()

Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [35]:
#primer array = 2x5x3
#segundo array = 3x2x5

#.reshape del segundo para que interactue con el primero.

segundo_cambiado = np.reshape (segundo_array, (2,5,3))
segundo_cambiado

array([[[29, 20, 26],
        [39, 33, 30],
        [35, 34, 28],
        [32, 24, 22],
        [34, 33, 32]],

       [[28, 26, 36],
        [28, 26, 36],
        [27, 32, 24],
        [25, 23, 34],
        [29, 31, 24]]])

In [37]:
suma = np.add(primer_array,segundo_cambiado)

In [45]:
#primer array = 2x5x3
#segundo array = 3x2x5

#.transpose del segundo para que interactue con el primero.

primero_cambiado = np.transpose (primer_array,(2,0,1))

In [46]:
primero_cambiado

array([[[34, 24, 28, 31, 32],
        [32, 20, 37, 38, 38]],

       [[23, 39, 38, 32, 20],
        [31, 27, 24, 29, 26]],

       [[25, 36, 38, 29, 29],
        [23, 30, 23, 25, 33]]])

In [48]:
suma = np.add(primero_cambiado,segundo_array)
suma

array([[[63, 44, 54, 70, 65],
        [62, 55, 71, 66, 70]],

       [[47, 61, 72, 65, 52],
        [59, 53, 60, 57, 52]],

       [[61, 63, 70, 53, 54],
        [46, 64, 52, 56, 57]]])