In [1]:
import numpy as np
import pandas as pd

**Pair Programming NumPy III**

En esta lección hemps aprendido algunas de las operaciones matemáticas más importantes que podemos aplicar a un array. Hoy pondremos en práctica algunas de estas operaciones, además de recordar algunas de los métodos aprendidos en otras lecciones y recordar como podemos iterar por un array.

Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:

In [2]:
array_3dim = np.random.random_sample((2,3,5))
array_3dim


array([[[0.18799748, 0.48921563, 0.29183631, 0.38690665, 0.09101844],
        [0.9427668 , 0.93396347, 0.45986807, 0.38796241, 0.9969473 ],
        [0.22790652, 0.06193786, 0.20184327, 0.9194169 , 0.34528259]],

       [[0.45238331, 0.31671907, 0.71404092, 0.6861516 , 0.71478878],
        [0.53191427, 0.87288651, 0.56559337, 0.47175585, 0.4471234 ],
        [0.51660833, 0.14126278, 0.59723469, 0.38966032, 0.056623  ]]])

In [3]:
array_redondeo = np.round(array_3dim, decimals = 1)
array_redondeo

array([[[0.2, 0.5, 0.3, 0.4, 0.1],
        [0.9, 0.9, 0.5, 0.4, 1. ],
        [0.2, 0.1, 0.2, 0.9, 0.3]],

       [[0.5, 0.3, 0.7, 0.7, 0.7],
        [0.5, 0.9, 0.6, 0.5, 0.4],
        [0.5, 0.1, 0.6, 0.4, 0.1]]])

Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [4]:
media_array = np.mean(array_redondeo)
media_array

0.48000000000000004

In [5]:
media_array_redondeado = np.round (media_array, decimals=1)
media_array_redondeado

0.5

Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [6]:
max_array = np.max(array_redondeo)

Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [7]:
min_array = np.min(array_redondeo)
min_array

0.1

Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.

In [8]:
array_vacio = np.empty((2,3,5))
array_vacio_1dec = np.round(array_vacio, decimals = 1)
array_vacio_1dec


array([[[0.2, 0.5, 0.3, 0.4, 0.1],
        [0.9, 0.9, 0.5, 0.4, 1. ],
        [0.2, 0.1, 0.2, 0.9, 0.3]],

       [[0.5, 0.3, 0.7, 0.7, 0.7],
        [0.5, 0.9, 0.6, 0.5, 0.4],
        [0.5, 0.1, 0.6, 0.4, 0.1]]])

Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor del array es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [9]:
array_vacio2 = np.empty((2,3,5), dtype=str)
array_vacio2

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [16]:
array_redondeo[0][0][0]

0.2

In [19]:
array_redondeo

array([[[0.2, 0.5, 0.3, 0.4, 0.1],
        [0.9, 0.9, 0.5, 0.4, 1. ],
        [0.2, 0.1, 0.2, 0.9, 0.3]],

       [[0.5, 0.3, 0.7, 0.7, 0.7],
        [0.5, 0.9, 0.6, 0.5, 0.4],
        [0.5, 0.1, 0.6, 0.4, 0.1]]])

In [17]:
array_redondeo.shape

(2, 3, 5)

In [27]:
for a in range(array_redondeo.shape[0]):

    for b in range(array_redondeo.shape[1]):
            
         for c in range(array_redondeo.shape[2]):
           
            if array_redondeo[a][b][c] == media_array :
                array_vacio2[a][b][c] = "A"

            elif array_redondeo[a][b][c] > media_array :
                array_vacio2[a][b][c] = "B"

            elif array_redondeo[a][b][c] < media_array :
                array_vacio2[a][b][c] = "C"

            elif array_redondeo[a][b][c] == max_array :
                array_vacio2[a][b][c] = "D"

            elif array_redondeo[a][b][c] == min_array :
                array_vacio2[a][b][c] = "E"
        

In [28]:
array_vacio2

array([[['C', 'B', 'C', 'C', 'C'],
        ['B', 'B', 'B', 'C', 'B'],
        ['C', 'C', 'C', 'B', 'C']],

       [['B', 'C', 'B', 'B', 'B'],
        ['B', 'B', 'B', 'B', 'C'],
        ['B', 'C', 'B', 'C', 'C']]], dtype='<U1')

Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos.  Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.



En este caso:
Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.
Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.