In [2]:
import numpy as np
import pandas as pd


**Pair Programming NumPy IV**

1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [3]:
np.random.seed(1)
array1 = np.random.sample(5)
array1

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01])

In [4]:
np.random.seed(1)
array2 = np.random.sample(5)
array2

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01])

2. Cread los siguientes arrays:
- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales.

In [5]:
array_tridimensional = np.random.randint(0, 10,(2,3,5))
array_tridimensional

array([[[0, 1, 7, 6, 9],
        [2, 4, 5, 2, 4],
        [2, 4, 7, 7, 9]],

       [[1, 7, 0, 6, 9],
        [9, 7, 6, 9, 1],
        [0, 1, 8, 8, 3]]])

- Extrae sus valores únicos almacenándolos en una variable.

In [6]:
valores_unicos = np.unique(array_tridimensional)
valores_unicos

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10.

In [7]:
array_tridimensional = np.random.binomial(10, 0.3, size = (2, 3,5))
array_tridimensional

array([[[2, 5, 1, 3, 6],
        [3, 4, 2, 4, 4],
        [0, 4, 6, 4, 2]],

       [[4, 1, 3, 5, 2],
        [2, 1, 0, 4, 2],
        [2, 3, 1, 3, 1]]])

- Extrae sus valores únicos y guarda los datos en una variable.

In [8]:
valores_unicos2 = np.unique(array_tridimensional)
valores_unicos2

array([0, 1, 2, 3, 4, 5, 6])

3. En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
⚠️ Explicar cada uno de los outputs que os salgan. ¿Que significa cada una de estas operaciones que hemos ido extrayendo?
- Elementos comunes entre los dos arrays.

In [9]:
elementos_comunes = np.intersect1d(valores_unicos, valores_unicos2)
elementos_comunes

#nos devuelve los valores únicos de la intersección ordenados, aquellos que se encuentran en ambos arrays.

array([0, 1, 2, 3, 4, 5, 6])

- Unión de los dos arrays.

In [10]:
union_dosarrays = np.union1d(valores_unicos, valores_unicos2)
union_dosarrays

#encuentra la unión de los dos arrays, devuelve un array ordenado con TODOS los elementos, no repetidos.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos.

In [11]:
elementos = np.setdiff1d(array_tridimensional, valores_unicos2)
elementos

array([], dtype=int64)

4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

In [12]:
array11 = np.random.randint (1,100, size=80)
array11

array([75, 63, 47, 33, 89, 24, 56, 66, 78,  4,  1, 78,  7, 53, 86, 71,  3,
       77, 92, 22, 76,  8, 78, 73, 76, 77, 44, 21, 31, 37,  8, 46, 69, 58,
       83, 97, 14, 11, 24, 82,  8, 25, 75, 93, 21, 33, 13, 66, 95, 61, 25,
       83, 98,  3, 93, 99, 11, 55, 97, 83, 87, 71, 67, 72, 49, 55, 16,  6,
       18, 43, 21, 49, 23, 14, 98, 54, 85, 11, 97, 56])

In [13]:
array22 = np.random.randint (1,100, size=80)
array22

array([62, 57, 90, 22, 97, 84, 26, 15, 14, 85, 44,  7, 78, 57, 60, 16, 25,
       10, 67, 72, 54, 70, 37, 22, 41, 78, 92, 50, 48, 78, 41, 79, 46, 88,
       17, 29, 46, 68, 67, 79, 47,  1, 30, 64, 76, 36, 54, 94, 34,  3, 85,
       84, 49, 55, 33, 29, 56, 83, 32, 29, 95, 75,  9, 33,  9, 85, 78, 51,
       80, 42, 65, 84, 25, 21, 45, 16, 31, 92, 15, 20])

- Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

In [14]:
array11 = np.unique(array11)
array11

array([ 1,  3,  4,  6,  7,  8, 11, 13, 14, 16, 18, 21, 22, 23, 24, 25, 31,
       33, 37, 43, 44, 46, 47, 49, 53, 54, 55, 56, 58, 61, 63, 66, 67, 69,
       71, 72, 73, 75, 76, 77, 78, 82, 83, 85, 86, 87, 89, 92, 93, 95, 97,
       98, 99])

In [15]:
array22 = np.unique(array22)
array22

array([ 1,  3,  7,  9, 10, 14, 15, 16, 17, 20, 21, 22, 25, 26, 29, 30, 31,
       32, 33, 34, 36, 37, 41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 54, 55,
       56, 57, 60, 62, 64, 65, 67, 68, 70, 72, 75, 76, 78, 79, 80, 83, 84,
       85, 88, 90, 92, 94, 95, 97])

- Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

In [16]:
array33 = np.setdiff1d(array11, array22)
array33

array([ 4,  6,  8, 11, 13, 18, 23, 24, 43, 53, 58, 61, 63, 66, 69, 71, 73,
       77, 82, 86, 87, 89, 93, 98, 99])

- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [17]:
array44 = np.setdiff1d(array22, array11)
array44

array([ 9, 10, 15, 17, 20, 26, 29, 30, 32, 34, 36, 41, 42, 45, 48, 50, 51,
       57, 60, 62, 64, 65, 68, 70, 79, 80, 84, 88, 90, 94])

- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [18]:
array55 = np.intersect1d (array11, array22)
array55

array([ 1,  3,  7, 14, 16, 21, 22, 25, 31, 33, 37, 44, 46, 47, 49, 54, 55,
       56, 67, 72, 75, 76, 78, 83, 85, 92, 95, 97])

- ¿Cuál es la relación que existe entre todos estos arrays?

💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [19]:
#los valores, si hemos estado trabajando con los mismos arrays all the time!

# la size no es la misma. 
# dtype si es el mismo = 'int64'
# ndim si son las mismas = 1
# shape es la misma en todos y es igual la size.
# len es el mismo a size y shape.

#para comparar los arrays podemos trabajar con la len y con la size.
#len: array11,60, y array44,23, == array22,56, y array33,27.-------- nos sobra array55

In [20]:
len11 = len(array11)
len11

53

In [21]:
len22 = len(array22)
len22

58

In [22]:
len33 = len(array33)
len33

25

In [23]:
len44 = len(array44)
len44

30

In [40]:
len55 = len(array55)
len55

28

---------------

In [24]:
size11 = array11.size
size11

53

In [25]:
size22 = array22.size
size22

58

In [26]:
size33 = array33.size
size33

25

In [36]:
size44 = array44.size
size44

30

In [41]:
size55 = array55.size
size55

28

---------------

In [27]:
dtype11 = array11.dtype
dtype11

dtype('int64')

In [28]:
dtype22 = array22.dtype
dtype22

dtype('int64')

In [29]:
dtype33 = array33.dtype
dtype33

dtype('int64')

In [37]:
dtype44 = array44.dtype
dtype44

dtype('int64')

In [42]:
dtype55 = array55.dtype
dtype55

dtype('int64')

---------------

In [30]:
dimen11 = array11.ndim
dimen11

1

In [31]:
dimen22 = array22.ndim
dimen22

1

In [32]:
dimen33 = array33.ndim
dimen33

1

In [38]:
dimen44 = array44.ndim
dimen44

1

In [43]:
dimen55 = array55.ndim
dimen55

1

---------------

In [33]:
shape11 = array11.shape
shape11

(53,)

In [34]:
shape22 = array22.shape
shape22

(58,)

In [35]:
shape33 = array33.shape
shape33

(25,)

In [39]:
shape44 = array44.shape
shape44

(30,)

In [44]:
shape55 = array55.shape
shape55

(28,)

---------------