In [4]:
import numpy as np
import pandas as pd

**Pair Programming NumPy I**

1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas en algunos casos.

  📌 Nota: El array de 2 dimensiones debe ser de 2 filas y 3 columnas.
El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas.

In [5]:
array_1dimension = np.random.randint(0,50, 5)
array_1dimension

array([ 5, 18,  5, 43, 40])

In [22]:
array_2dimensiones = np.random.randint(0,50,(2,3))
array_2dimensiones

array([[ 0, 18, 18],
       [ 1, 42,  5]])

In [7]:
array_3dimensiones = np.random.randint(0,50,(2,3,5))
array_3dimensiones

array([[[28, 18, 47,  9, 20],
        [40, 30, 20, 29, 15],
        [29, 24, 42, 16, 46]],

       [[16, 29,  0,  1, 38],
        [14, 32,  2, 46, 15],
        [ 9, 47, 44, 36, 30]]])


2. Chequead las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de un array que le pasemos.

In [8]:
array_2dimensiones.shape 

(2, 3)

In [12]:
array_3dimensiones.shape 

(2, 3, 5)

In [9]:
array_2dimensiones.size

6

In [13]:
array_3dimensiones.size

30

In [10]:
array_2dimensiones.ndim

2

In [14]:
array_3dimensiones.ndim

3

In [11]:
array_2dimensiones.dtype

dtype('int64')

In [15]:
array_3dimensiones.dtype

dtype('int64')

3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas.

In [16]:
matriz_identidad = np.identity(5)
matriz_identidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [25]:
matriz_unos = np.ones_like(array_3dimensiones)
matriz_unos

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

5. Es el momento de hacer algunas operaciones entre arrays.
- ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?
En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

In [ ]:
#no se pueden sumar por que no tienen la misma forma ni las mismas dimensiones.

In [24]:
array_2dimensiones_mod = np.random.randint(0,50,(5,5))
array_2dimensiones_mod

array([[18, 12, 29, 18,  4],
       [49, 43, 34, 39, 37],
       [32, 49, 36,  6, 24],
       [27, 25, 11, 16, 38],
       [39,  0, 41, 16, 37]])

In [27]:
suma = np.add(matriz_identidad,array_2dimensiones_mod)
suma

array([[19., 12., 29., 18.,  4.],
       [49., 44., 34., 39., 37.],
       [32., 49., 37.,  6., 24.],
       [27., 25., 11., 17., 38.],
       [39.,  0., 41., 16., 38.]])

- Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

In [29]:
multiplicacion = np.multiply(matriz_identidad, array_2dimensiones_mod)
multiplicacion

array([[18.,  0.,  0.,  0.,  0.],
       [ 0., 43.,  0.,  0.,  0.],
       [ 0.,  0., 36.,  0.,  0.],
       [ 0.,  0.,  0., 16.,  0.],
       [ 0.,  0.,  0.,  0., 37.]])

- Dividid las dos matrices.

In [37]:
div = np.divide(matriz_identidad, array_2dimensiones_mod)
div

/var/folders/qq/jtqr5_ts3_5frnqgj2ky0sjr0000gn/T/ipykernel_17438/1360652678.py:1: RuntimeWarning: invalid value encountered in true_divide
  div = np.divide(matriz_identidad, array_2dimensiones_mod)


array([[0.05555556, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.02325581, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.02777778, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.0625    , 0.        ],
       [0.        ,        nan, 0.        , 0.        , 0.02702703]])

In [38]:
div2 = np.divide(array_2dimensiones_mod, matriz_identidad )
div2

/var/folders/qq/jtqr5_ts3_5frnqgj2ky0sjr0000gn/T/ipykernel_17438/3540778571.py:1: RuntimeWarning: divide by zero encountered in true_divide
  div2 = np.divide(array_2dimensiones_mod, matriz_identidad )
/var/folders/qq/jtqr5_ts3_5frnqgj2ky0sjr0000gn/T/ipykernel_17438/3540778571.py:1: RuntimeWarning: invalid value encountered in true_divide
  div2 = np.divide(array_2dimensiones_mod, matriz_identidad )


array([[18., inf, inf, inf, inf],
       [inf, 43., inf, inf, inf],
       [inf, inf, 36., inf, inf],
       [inf, inf, inf, 16., inf],
       [inf, nan, inf, inf, 37.]])