In [1]:
import numpy as np
import pandas as pd

**Pair Programming NumPy II**

1.- Cread un array de dos dimensiones de 5 filas y 3 columnas.
Sobre el array creado anteriormente, extraed:

In [2]:
bidimensional = np.random.rand(5, 3)
bidimensional

array([[0.65941409, 0.34690316, 0.510392  ],
       [0.52167416, 0.55347569, 0.90988956],
       [0.23019123, 0.85422532, 0.7653243 ],
       [0.939183  , 0.84629606, 0.86625944],
       [0.42366987, 0.27472739, 0.17420852]])

- El valor de la primera fila y la segunda columna.

In [3]:
bidimensional[0,1]

0.34690315921566073

- Los valores de la segunda fila y las dos primeras columnas.

In [4]:
bidimensional[1,0:2]

array([0.52167416, 0.55347569])

- Extraed las filas pares (incluyendo la 0) y todas las columnas.

In [5]:
bidimensional[0::2,:]

array([[0.65941409, 0.34690316, 0.510392  ],
       [0.23019123, 0.85422532, 0.7653243 ],
       [0.42366987, 0.27472739, 0.17420852]])

- Extraed los valores que sean mayores que 0.5.

In [6]:
bidimensional[bidimensional > 0.5]

array([0.65941409, 0.510392  , 0.52167416, 0.55347569, 0.90988956,
       0.85422532, 0.7653243 , 0.939183  , 0.84629606, 0.86625944])

- Extraed los valores menores que 0.2 o mayores que 0.5

In [7]:
bidimensional[(bidimensional < 0.2) | (bidimensional > 0.5)]

array([0.65941409, 0.510392  , 0.52167416, 0.55347569, 0.90988956,
       0.85422532, 0.7653243 , 0.939183  , 0.84629606, 0.86625944,
       0.17420852])

2.- Cread dos array de tres dimensiones:
El primero de 2 matrices, 5 filas y 3 columnas.
El segundo de 3 matrices, 2 filas y 5 columnas.

In [8]:
primer_array = np.random.randint(20,40,(2,5,3))
primer_array

array([[[24, 38, 25],
        [20, 34, 30],
        [38, 37, 20],
        [30, 38, 34],
        [28, 23, 22]],

       [[35, 25, 30],
        [23, 35, 26],
        [32, 31, 22],
        [28, 26, 31],
        [27, 31, 37]]])

In [9]:
segundo_array = np.random.randint(20,40,(3,2,5))
segundo_array

array([[[21, 34, 37, 29, 23],
        [28, 25, 39, 27, 27]],

       [[22, 29, 38, 24, 23],
        [37, 32, 36, 37, 32]],

       [[38, 37, 35, 33, 20],
        [23, 26, 36, 39, 33]]])

Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [10]:
def propiedades_array(array):
    tipo=f"Los elementos son de tipo {array.dtype}"
    tamaño=f"Tiene {array.size} elementos"
    forma=f"Su forma es: {array.shape}"
    dimension=f"Es de {array.ndim} dimensiones"
    return tipo,tamaño,forma,dimension

In [11]:
propiedades_array (primer_array)

('Los elementos son de tipo int64',
 'Tiene 30 elementos',
 'Su forma es: (2, 5, 3)',
 'Es de 3 dimensiones')

In [12]:
propiedades_array (segundo_array)

('Los elementos son de tipo int64',
 'Tiene 30 elementos',
 'Su forma es: (3, 2, 5)',
 'Es de 3 dimensiones')

Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [13]:
#No se puede por que no tienen la misma forma.

Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas
formas hemos aprendido dos métodos:
- .reshape()
- .transpose()

Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [14]:
#primer array = 2x5x3
#segundo array = 3x2x5

#.reshape del segundo para que interactue con el primero.

segundo_cambiado = np.reshape (segundo_array, (2,5,3))
segundo_cambiado

array([[[21, 34, 37],
        [29, 23, 28],
        [25, 39, 27],
        [27, 22, 29],
        [38, 24, 23]],

       [[37, 32, 36],
        [37, 32, 38],
        [37, 35, 33],
        [20, 23, 26],
        [36, 39, 33]]])

In [15]:
suma = np.add(primer_array,segundo_cambiado)

In [16]:
#primer array = 2x5x3
#segundo array = 3x2x5

#.transpose del segundo para que interactue con el primero.

primero_cambiado = np.transpose (primer_array,(2,0,1))

In [17]:
primero_cambiado

array([[[24, 20, 38, 30, 28],
        [35, 23, 32, 28, 27]],

       [[38, 34, 37, 38, 23],
        [25, 35, 31, 26, 31]],

       [[25, 30, 20, 34, 22],
        [30, 26, 22, 31, 37]]])

In [18]:
suma = np.add(primero_cambiado,segundo_array)
suma

array([[[45, 54, 75, 59, 51],
        [63, 48, 71, 55, 54]],

       [[60, 63, 75, 62, 46],
        [62, 67, 67, 63, 63]],

       [[63, 67, 55, 67, 42],
        [53, 52, 58, 70, 70]]])